server.port=8814
spring.application.name=payment-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_microservices_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

payment.vnpay.tmn-code=${VNPAY_TMN_CODE}
payment.vnpay.hash-secret=${VNPAY_HASH_SECRET}
payment.vnpay.payment-url=${VNPAY_PAYMENT_URL}
payment.vnpay.query-url=${VNPAY_QUERY_URL}
payment.vnpay.return-url=${VNPAY_RETURN_URL}
payment.vnpay.ipn-url=${VNPAY_IPN_URL:}
payment.vnpay.ipn-enabled=${VNPAY_IPN_ENABLED:false}
payment.vnpay.frontend-result-url=${FRONTEND_RESULT_URL}
payment.vnpay.version=${VNPAY_VERSION:2.1.0}
payment.vnpay.command=${VNPAY_COMMAND:pay}
payment.vnpay.order-type=${VNPAY_ORDER_TYPE:other}
payment.vnpay.locale=${VNPAY_LOCALE:vn}
