##### Service details: #####
server.port= 8811
spring.application.name= user-service
server.url= http://localhost:8811

#Client registration properties :
eureka.client.service-url.defaultZone = http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

#Data source :
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_microservices_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

#Jpa/Hibernate :
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update

##### HTTP #####
error.404.schema.details=The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable
error.406.schema.details=This request is not acceptable. Supported MIME types are application/json

# JWT Config
jwt.secret=9a4f2c8d3b7a1e5f8g9h0i1j2k3l4m5n6o7p8q9r0s1t2u3v4w5x6y7z8a9b0c1d
jwt.expiration=86400000

# Email Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ungthithanhthao611@gmail.com
spring.mail.password=rstjtxntmgvelkth
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true